version: "2"

services:
  meli-bff:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: yarn start -- -L
    environment:
      - NODE_ENV=production
